### ISSUE TITLE
Sign out button not visible

### ISSUE THREAD

**Issue by VangelisTheodorakis** [nephantes/dolphinnext-tutorial#3]
So as you can see I used the nextflow tutorial but the sign out button is off place.
Is this a know bug of the specific docker image?

![Screenshot-2019-11-11 Test Server DolphinNext Pipeline Builder](https://user-images.githubusercontent.com/2484965/68579774-44317c80-0475-11ea-8e5d-3dc65d945fda.png)

**Comment by nephantes** [comment]
What is your browser? This is not something we see.

**Comment by VangelisTheodorakis** [comment]
Firefox 60.9.0esr (64-bit) on CentOS 7 but I think this is the problem. 
I just tried to connect from my phone and it works fine.

Otherwise the problem may lay on the docker image?

**Comment by nephantes** [comment]
Looks like, it is browser. You can use 'Google Chrome' for now until we fix.

**Comment by VangelisTheodorakis** [comment]
Yeah it is a browser bug. I just confirmed it, on CentOS 7 Google Chrome 
and Android Firefox it works fine.

**Comment by onuryukselen** [comment]
Issue fixed in Version 1.0.0 #211
